Remove column from WooCommerce products
robincornett/add-featured-image-column pull request #2
Opened 2020-09-25 17:58 UTC by JiveDig

Fixes https://github.com/robincornett/add-featured-image-column/issues/1

2020-09-26 12:25 UTC, robincornett requested changes
I think my preference would be to do the check and remove `product` from the `$post_types` array before the filter (`addfeaturedimagecolumn_post_types`) is applied. That way, if someone wanted to re-enable this column in preference of the WC one, they still could?

```php
		if ( class_exists( 'WooCommerce' ) ) {
			unset( $post_types['product'] );
		}
		$post_types = apply_filters( 'addfeaturedimagecolumn_post_types', $post_types, $args );
```

I'll concede that it's not likely anyone would bother, but would still leave the option open.

2020-09-26 13:20 UTC, JiveDig commented
I should have scanned the code further, that's definitely the better place to do it. 

I can adjust next time at my comp 👍

2020-09-28 13:51 UTC, JiveDig commented
Updated :)

2020-09-28 14:25 UTC, robincornett approved these changes

2020-09-28 14:25 UTC, merged